import { NextResponse } from "next/server";
import { ASIA_CITIES } from "@/lib/asia-cities";

/** Featured first so autocomplete isn't US-only when the field is empty */
const FEATURED = [
  "Remote",
  "United States",
  "United Kingdom",
  "Canada",
  "Germany",
  "France",
  "Netherlands",
  "Spain",
  "Portugal",
  "Poland",
  "Ukraine",
  "India",
  "Japan",
  "South Korea",
  "Singapore",
  "Australia",
  "Brazil",
  "Argentina",
  "Mexico",
  "Nigeria",
  "South Africa",
  "Kenya",
  "Egypt",
  "United Arab Emirates",
  "Israel",
  "Turkey",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Switzerland",
  "Italy",
  "Ireland",
  "Czech Republic",
  "Romania",
  "Vietnam",
  "Philippines",
  "Indonesia",
  "Thailand",
  "China",
  "Taiwan",
  "Hong Kong",
  "New Zealand",
  "Colombia",
  "Chile",
  "Peru",
];

/** All countries / territories commonly used in GitHub location fields */
const ALL_COUNTRIES = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Czechia",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
  // Common aliases / regions
  "UK",
  "USA",
  "UAE",
  "England",
  "Scotland",
  "Wales",
  "Northern Ireland",
  "Europe",
  "Asia",
  "Africa",
  "Latin America",
  "Middle East",
  "Southeast Asia",
  "Eastern Europe",
  "Western Europe",
];

const CITIES = [
  // Featured metro hubs
  "London",
  "Berlin",
  "Amsterdam",
  "Paris",
  "Toronto",
  "Vancouver",
  "São Paulo",
  "Bangalore",
  "Bengaluru",
  "Hyderabad",
  "Tokyo",
  "Sydney",
  "Dubai",
  "Lagos",
  "Nairobi",
  "Warsaw",
  "Lisbon",
  "Madrid",
  "Barcelona",
  "Munich",
  "Stockholm",
  "Dublin",
  "Tel Aviv",
  "Seoul",
  "Jakarta",
  "Manila",
  "Ho Chi Minh City",
  "Mexico City",
  "Buenos Aires",
  "Santiago",
  "Bogotá",

  // United States
  "San Francisco, CA",
  "San Francisco",
  "New York, NY",
  "New York",
  "Seattle, WA",
  "Seattle",
  "Austin, TX",
  "Austin",
  "Boston, MA",
  "Boston",
  "Los Angeles, CA",
  "Los Angeles",
  "Chicago, IL",
  "Chicago",
  "Denver, CO",
  "Denver",
  "Portland, OR",
  "Portland",
  "Atlanta, GA",
  "Atlanta",
  "Miami, FL",
  "Miami",
  "San Diego, CA",
  "San Diego",
  "Washington, DC",
  "Washington DC",
  "Dallas, TX",
  "Dallas",
  "Houston, TX",
  "Houston",
  "Phoenix, AZ",
  "Phoenix",
  "Minneapolis, MN",
  "Minneapolis",
  "Philadelphia, PA",
  "Philadelphia",
  "Raleigh, NC",
  "Raleigh",
  "Salt Lake City, UT",
  "Salt Lake City",
  "San Jose, CA",
  "San Jose",
  "Palo Alto, CA",
  "Mountain View, CA",
  "Cupertino, CA",
  "Redmond, WA",
  "Bellevue, WA",
  "Brooklyn, NY",
  "Queens, NY",
  "Jersey City, NJ",
  "Princeton, NJ",
  "Pittsburgh, PA",
  "Detroit, MI",
  "Ann Arbor, MI",
  "Columbus, OH",
  "Cincinnati, OH",
  "Cleveland, OH",
  "Indianapolis, IN",
  "Nashville, TN",
  "Charlotte, NC",
  "Durham, NC",
  "Chapel Hill, NC",
  "Tampa, FL",
  "Orlando, FL",
  "Jacksonville, FL",
  "New Orleans, LA",
  "Kansas City, MO",
  "St. Louis, MO",
  "Madison, WI",
  "Milwaukee, WI",
  "Boulder, CO",
  "Colorado Springs, CO",
  "Albuquerque, NM",
  "Tucson, AZ",
  "Las Vegas, NV",
  "Reno, NV",
  "Sacramento, CA",
  "Oakland, CA",
  "Berkeley, CA",
  "Irvine, CA",
  "Santa Monica, CA",
  "Pasadena, CA",
  "California",
  "Texas",
  "New York State",
  "Washington",
  "Massachusetts",
  "Colorado",
  "Florida",
  "Illinois",
  "Georgia",
  "Virginia",
  "North Carolina",
  "Oregon",
  "Arizona",
  "Utah",
  "Michigan",
  "Pennsylvania",
  "Ohio",
  "New Jersey",
  "Maryland",
  "Connecticut",

  // Canada
  "Montreal, QC",
  "Montreal",
  "Calgary, AB",
  "Calgary",
  "Ottawa, ON",
  "Ottawa",
  "Edmonton, AB",
  "Edmonton",
  "Winnipeg, MB",
  "Winnipeg",
  "Victoria, BC",
  "Victoria",
  "Quebec City",
  "Kitchener",
  "Waterloo",
  "Hamilton",
  "Mississauga",
  "Burnaby",

  // Mexico & LatAm
  "Guadalajara",
  "Monterrey",
  "Tijuana",
  "Puebla",
  "Querétaro",
  "Medellín",
  "Cali",
  "Cartagena",
  "Lima",
  "Arequipa",
  "Rio de Janeiro",
  "Curitiba",
  "Belo Horizonte",
  "Brasília",
  "Porto Alegre",
  "Recife",
  "Florianópolis",
  "Campinas",
  "Córdoba",
  "Rosario",
  "Mendoza",
  "Montevideo",
  "Quito",
  "Guayaquil",
  "La Paz",
  "Santa Cruz",
  "Asunción",
  "Caracas",
  "Valparaíso",
  "Concepción",
  "San José",
  "Panama City",
  "Guatemala City",
  "San Salvador",
  "Tegucigalpa",
  "Managua",
  "Havana",
  "Santo Domingo",
  "Kingston",
  "Port of Spain",

  // UK & Ireland
  "Manchester",
  "Edinburgh",
  "Birmingham",
  "Glasgow",
  "Bristol",
  "Leeds",
  "Liverpool",
  "Sheffield",
  "Newcastle",
  "Nottingham",
  "Cambridge",
  "Oxford",
  "Reading",
  "Brighton",
  "Cardiff",
  "Belfast",
  "Cork",
  "Galway",
  "Limerick",
  "Waterford",

  // Western Europe
  "Hamburg",
  "Frankfurt",
  "Cologne",
  "Düsseldorf",
  "Stuttgart",
  "Leipzig",
  "Dresden",
  "Nuremberg",
  "Hannover",
  "Dortmund",
  "Essen",
  "Bonn",
  "Karlsruhe",
  "Aachen",
  "Lyon",
  "Marseille",
  "Toulouse",
  "Nantes",
  "Lille",
  "Bordeaux",
  "Nice",
  "Grenoble",
  "Strasbourg",
  "Rennes",
  "Montpellier",
  "Brussels",
  "Antwerp",
  "Ghent",
  "Bruges",
  "Liège",
  "Rotterdam",
  "The Hague",
  "Utrecht",
  "Eindhoven",
  "Groningen",
  "Zurich",
  "Geneva",
  "Basel",
  "Bern",
  "Lausanne",
  "Vienna",
  "Graz",
  "Linz",
  "Salzburg",
  "Innsbruck",
  "Luxembourg",
  "Monaco",

  // Southern Europe
  "Valencia",
  "Seville",
  "Zaragoza",
  "Málaga",
  "Bilbao",
  "Murcia",
  "Palma",
  "Granada",
  "Porto",
  "Braga",
  "Coimbra",
  "Faro",
  "Milan",
  "Rome",
  "Turin",
  "Naples",
  "Bologna",
  "Florence",
  "Genoa",
  "Padua",
  "Venice",
  "Verona",
  "Athens",
  "Thessaloniki",
  "Patras",
  "Nicosia",
  "Limassol",
  "Valletta",

  // Northern Europe
  "Copenhagen",
  "Aarhus",
  "Odense",
  "Aalborg",
  "Oslo",
  "Bergen",
  "Trondheim",
  "Stavanger",
  "Helsinki",
  "Tampere",
  "Espoo",
  "Turku",
  "Oulu",
  "Reykjavik",
  "Gothenburg",
  "Malmö",
  "Uppsala",
  "Linköping",
  "Lund",

  // Eastern Europe
  "Kraków",
  "Wrocław",
  "Gdańsk",
  "Poznań",
  "Łódź",
  "Katowice",
  "Lublin",
  "Prague",
  "Brno",
  "Ostrava",
  "Budapest",
  "Debrecen",
  "Szeged",
  "Bucharest",
  "Cluj-Napoca",
  "Timișoara",
  "Iași",
  "Brașov",
  "Sofia",
  "Plovdiv",
  "Varna",
  "Belgrade",
  "Novi Sad",
  "Zagreb",
  "Split",
  "Kyiv",
  "Lviv",
  "Kharkiv",
  "Odesa",
  "Dnipro",
  "Riga",
  "Vilnius",
  "Kaunas",
  "Tallinn",
  "Tartu",
  "Bratislava",
  "Ljubljana",
  "Sarajevo",
  "Skopje",
  "Podgorica",
  "Tirana",
  "Chișinău",
  "Moscow",
  "Saint Petersburg",
  "Novosibirsk",
  "Yekaterinburg",
  "Kazan",
  "Minsk",
  "Tbilisi",
  "Yerevan",
  "Baku",
  "Almaty",
  "Astana",
  "Nur-Sultan",
  "Tashkent",

  // Middle East
  "Istanbul",
  "Ankara",
  "Izmir",
  "Bursa",
  "Antalya",
  "Abu Dhabi",
  "Sharjah",
  "Riyadh",
  "Jeddah",
  "Dammam",
  "Doha",
  "Kuwait City",
  "Manama",
  "Muscat",
  "Amman",
  "Beirut",
  "Cairo",
  "Alexandria",
  "Giza",
  "Casablanca",
  "Rabat",
  "Marrakech",
  "Tangier",
  "Tunis",
  "Sfax",
  "Jerusalem",
  "Haifa",
  "Beer Sheva",

  // Africa
  "Abuja",
  "Ibadan",
  "Port Harcourt",
  "Kano",
  "Enugu",
  "Accra",
  "Kumasi",
  "Cape Town",
  "Johannesburg",
  "Pretoria",
  "Durban",
  "Port Elizabeth",
  "Gqeberha",
  "Mombasa",
  "Kisumu",
  "Addis Ababa",
  "Kampala",
  "Kigali",
  "Dar es Salaam",
  "Dodoma",
  "Algiers",
  "Oran",
  "Dakar",
  "Abidjan",
  "Yaoundé",
  "Douala",
  "Lusaka",
  "Harare",
  "Gaborone",
  "Windhoek",
  "Maputo",
  "Luanda",
  "Antananarivo",
  "Port Louis",
  "Khartoum",
  "Juba",

  // South Asia
  "Mumbai",
  "Delhi",
  "New Delhi",
  "Pune",
  "Chennai",
  "Kolkata",
  "Ahmedabad",
  "Noida",
  "Gurgaon",
  "Gurugram",
  "Kochi",
  "Cochin",
  "Jaipur",
  "Chandigarh",
  "Indore",
  "Bhopal",
  "Lucknow",
  "Coimbatore",
  "Thiruvananthapuram",
  "Visakhapatnam",
  "Mysore",
  "Mysuru",
  "Nagpur",
  "Surat",
  "Islamabad",
  "Karachi",
  "Lahore",
  "Rawalpindi",
  "Dhaka",
  "Chittagong",
  "Colombo",
  "Kandy",
  "Kathmandu",
  "Pokhara",
  "Thimphu",

  // East / SE Asia
  "Osaka",
  "Kyoto",
  "Yokohama",
  "Nagoya",
  "Fukuoka",
  "Sapporo",
  "Kobe",
  "Busan",
  "Incheon",
  "Daejeon",
  "Beijing",
  "Shanghai",
  "Shenzhen",
  "Guangzhou",
  "Hangzhou",
  "Chengdu",
  "Nanjing",
  "Wuhan",
  "Xi'an",
  "Suzhou",
  "Tianjin",
  "Chongqing",
  "Taipei",
  "Kaohsiung",
  "Taichung",
  "Hanoi",
  "Da Nang",
  "Haiphong",
  "Bangkok",
  "Chiang Mai",
  "Phuket",
  "Kuala Lumpur",
  "Penang",
  "Johor Bahru",
  "Ipoh",
  "Surabaya",
  "Bandung",
  "Medan",
  "Bali",
  "Denpasar",
  "Cebu",
  "Makati",
  "Quezon City",
  "Davao",
  "Phnom Penh",
  "Siem Reap",
  "Vientiane",
  "Yangon",
  "Mandalay",
  "Ulaanbaatar",

  // Oceania
  "Melbourne",
  "Brisbane",
  "Perth",
  "Adelaide",
  "Canberra",
  "Gold Coast",
  "Hobart",
  "Darwin",
  "Auckland",
  "Wellington",
  "Christchurch",
  "Hamilton, NZ",
  "Dunedin",
  "Suva",
];

/** Extra cities, metros, states, and aliases people put on GitHub */
const MORE_LOCATIONS = [
  // Metros / regions
  "Bay Area",
  "Silicon Valley",
  "SF Bay Area",
  "Greater London",
  "Greater Toronto Area",
  "GTA",
  "DMV",
  "Tri-State",
  "Pacific Northwest",
  "PNW",
  "New England",
  "Midwest",
  "SoCal",
  "NorCal",
  "Southern California",
  "Northern California",
  "Research Triangle",
  "RTP",
  "Twin Cities",
  "Remote - Worldwide",
  "Remote - US",
  "Remote - Europe",
  "Remote - UK",
  "Remote - Canada",
  "Remote - India",
  "Worldwide",
  "Earth",
  "Global",
  "Anywhere",
  "Open to Remote",

  // US states (full names — common on GitHub)
  "Alabama",
  "Alaska",
  "Arkansas",
  "Delaware",
  "Hawaii",
  "Idaho",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Mexico",
  "North Dakota",
  "Oklahoma",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Vermont",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
  "District of Columbia",

  // More US cities
  "Albany, NY",
  "Buffalo, NY",
  "Rochester, NY",
  "Syracuse, NY",
  "White Plains, NY",
  "Stamford, CT",
  "Hartford, CT",
  "New Haven, CT",
  "Providence, RI",
  "Worcester, MA",
  "Cambridge, MA",
  "Somerville, MA",
  "Waltham, MA",
  "Burlington, VT",
  "Portland, ME",
  "Manchester, NH",
  "Portsmouth, NH",
  "Newark, NJ",
  "Hoboken, NJ",
  "Morristown, NJ",
  "Baltimore, MD",
  "Bethesda, MD",
  "Rockville, MD",
  "Arlington, VA",
  "Alexandria, VA",
  "Reston, VA",
  "McLean, VA",
  "Fairfax, VA",
  "Richmond, VA",
  "Norfolk, VA",
  "Virginia Beach, VA",
  "Charlottesville, VA",
  "Charleston, SC",
  "Columbia, SC",
  "Greenville, SC",
  "Asheville, NC",
  "Greensboro, NC",
  "Winston-Salem, NC",
  "Knoxville, TN",
  "Memphis, TN",
  "Chattanooga, TN",
  "Louisville, KY",
  "Lexington, KY",
  "Birmingham, AL",
  "Huntsville, AL",
  "Mobile, AL",
  "Jackson, MS",
  "Little Rock, AR",
  "Oklahoma City, OK",
  "Tulsa, OK",
  "Omaha, NE",
  "Lincoln, NE",
  "Des Moines, IA",
  "Cedar Rapids, IA",
  "Wichita, KS",
  "Kansas City, KS",
  "Fargo, ND",
  "Sioux Falls, SD",
  "Boise, ID",
  "Spokane, WA",
  "Tacoma, WA",
  "Olympia, WA",
  "Eugene, OR",
  "Bend, OR",
  "Salem, OR",
  "Anchorage, AK",
  "Honolulu, HI",
  "Fresno, CA",
  "Bakersfield, CA",
  "Long Beach, CA",
  "Santa Barbara, CA",
  "Santa Cruz, CA",
  "San Mateo, CA",
  "Redwood City, CA",
  "Menlo Park, CA",
  "Sunnyvale, CA",
  "Santa Clara, CA",
  "Milpitas, CA",
  "Fremont, CA",
  "Pleasanton, CA",
  "Walnut Creek, CA",
  "Concord, CA",
  "Richmond, CA",
  "San Rafael, CA",
  "Scottsdale, AZ",
  "Mesa, AZ",
  "Tempe, AZ",
  "Chandler, AZ",
  "Flagstaff, AZ",
  "Provo, UT",
  "Ogden, UT",
  "Park City, UT",
  "Fort Collins, CO",
  "Colorado Springs",
  "Aspen, CO",
  "Santa Fe, NM",
  "El Paso, TX",
  "San Antonio, TX",
  "Fort Worth, TX",
  "Plano, TX",
  "Irving, TX",
  "Arlington, TX",
  "Round Rock, TX",
  "College Station, TX",
  "Tallahassee, FL",
  "St. Petersburg, FL",
  "Fort Lauderdale, FL",
  "West Palm Beach, FL",
  "Gainesville, FL",
  "Savannah, GA",
  "Athens, GA",
  "Augusta, GA",
  "Ann Arbor",
  "Grand Rapids, MI",
  "Lansing, MI",
  "Cincinnati",
  "Dayton, OH",
  "Toledo, OH",
  "Akron, OH",
  "Fort Wayne, IN",
  "Bloomington, IN",
  "Evanston, IL",
  "Naperville, IL",
  "Schaumburg, IL",
  "Milwaukee",
  "Madison",
  "St. Paul, MN",
  "Rochester, MN",
  "Kansas City",
  "St. Louis",

  // Canada more
  "Halifax",
  "St. John's",
  "Saskatoon",
  "Regina",
  "London, ON",
  "Windsor",
  "London Ontario",
  "Kelowna",
  "Surrey",
  "Richmond, BC",
  "Victoria, Canada",
  "Gatineau",
  "Laval",
  "Sherbrooke",
  "Trois-Rivières",
  "Markham",
  "Vaughan",
  "Brampton",
  "Oakville",
  "Burlington, ON",
  "Waterloo, ON",
  "Kitchener-Waterloo",

  // UK / Ireland more
  "Bath",
  "York",
  "Coventry",
  "Leicester",
  "Southampton",
  "Portsmouth",
  "Bournemouth",
  "Exeter",
  "Plymouth",
  "Norwich",
  "Ipswich",
  "Canterbury",
  "Guildford",
  "Slough",
  "Milton Keynes",
  "Swindon",
  "Aberdeen",
  "Dundee",
  "Inverness",
  "Swansea",
  "Newport",
  "Derry",
  "Londonderry",
  "Kilkenny",
  "Sligo",
  "Drogheda",

  // Europe more
  "Mannheim",
  "Heidelberg",
  "Freiburg",
  "Ulm",
  "Augsburg",
  "Regensburg",
  "Mainz",
  "Wiesbaden",
  "Kiel",
  "Rostock",
  "Bremen",
  "Potsdam",
  "Jena",
  "Erfurt",
  "Bochum",
  "Wuppertal",
  "Münster",
  "Bielefeld",
  "Braunschweig",
  "Clermont-Ferrand",
  "Dijon",
  "Angers",
  "Le Mans",
  "Tours",
  "Orléans",
  "Reims",
  "Metz",
  "Nancy",
  "Aix-en-Provence",
  "Cannes",
  "Toulon",
  "Perpignan",
  "Pau",
  "Brest",
  "Rouen",
  "Caen",
  "Amiens",
  "Maastricht",
  "Tilburg",
  "Breda",
  "Nijmegen",
  "Arnhem",
  "Haarlem",
  "Leiden",
  "Delft",
  "Almere",
  "Zwolle",
  "Leuven",
  "Charleroi",
  "Namur",
  "Mons",
  "Lugano",
  "Winterthur",
  "St. Gallen",
  "Lucerne",
  "Biel",
  "Fribourg",
  "Klagenfurt",
  "Linz, Austria",
  "Seville, Spain",
  "Alicante",
  "Córdoba, Spain",
  "Valladolid",
  "Vigo",
  "A Coruña",
  "Oviedo",
  "Santander",
  "Pamplona",
  "San Sebastián",
  "Donostia",
  "Girona",
  "Tarragona",
  "Aveiro",
  "Funchal",
  "Ponta Delgada",
  "Setúbal",
  "Évora",
  "Brescia",
  "Bergamo",
  "Parma",
  "Modena",
  "Pisa",
  "Siena",
  "Perugia",
  "Bari",
  "Catania",
  "Palermo",
  "Cagliari",
  "Trieste",
  "Trento",
  "Bolzano",
  "Udine",
  "Ancona",
  "Rimini",
  "Livorno",
  "Heraklion",
  "Rhodes",
  "Ioannina",
  "Larissa",
  "Volos",
  "Gothenburg, Sweden",
  "Umeå",
  "Örebro",
  "Västerås",
  "Helsingborg",
  "Jönköping",
  "Karlstad",
  "Linkoping",
  "Tromsø",
  "Kristiansand",
  "Drammen",
  "Espoo, Finland",
  "Vantaa",
  "Jyväskylä",
  "Kuopio",
  "Lahti",
  "Aalborg, Denmark",
  "Odense, Denmark",
  "Reykjavík",
  "Akureyri",
  "Szczecin",
  "Bydgoszcz",
  "Białystok",
  "Rzeszów",
  "Gdynia",
  "Sopot",
  "Toruń",
  "Kielce",
  "Olsztyn",
  "Opole",
  "Zielona Góra",
  "Plzeň",
  "Liberec",
  "Olomouc",
  "České Budějovice",
  "Hradec Králové",
  "Košice",
  "Žilina",
  "Prešov",
  "Nitra",
  "Debrecen, Hungary",
  "Pécs",
  "Győr",
  "Miskolc",
  "Szeged, Hungary",
  "Constanța",
  "Craiova",
  "Galați",
  "Oradea",
  "Sibiu",
  "Ploiești",
  "Arad",
  "Varna, Bulgaria",
  "Burgas",
  "Ruse",
  "Niš",
  "Kragujevac",
  "Subotica",
  "Rijeka",
  "Osijek",
  "Zadar",
  "Dubrovnik",
  "Maribor",
  "Banja Luka",
  "Mostar",
  "Priština",
  "Pristina",
  "Zaporizhzhia",
  "Vinnytsia",
  "Poltava",
  "Chernihiv",
  "Sumy",
  "Mykolaiv",
  "Mariupol",
  "Kaunas, Lithuania",
  "Klaipėda",
  "Šiauliai",
  "Liepāja",
  "Daugavpils",
  "Narva",
  "Pärnu",
  "Gomel",
  "Brest, Belarus",
  "Vitebsk",
  "Hrodna",
  "Rostov-on-Don",
  "Nizhny Novgorod",
  "Samara",
  "Chelyabinsk",
  "Ufa",
  "Krasnoyarsk",
  "Voronezh",
  "Perm",
  "Volgograd",
  "Krasnodar",
  "Sochi",
  "Tomsk",
  "Irkutsk",
  "Vladivostok",
  "Kaliningrad",
  "Batumi",
  "Kutaisi",
  "Gyumri",
  "Ganja",
  "Shymkent",
  "Karaganda",
  "Aktau",
  "Samarkand",
  "Bukhara",
  "Bishkek",
  "Osh",
  "Dushanbe",
  "Ashgabat",

  // Middle East / Africa more
  "Gaziantep",
  "Konya",
  "Adana",
  "Mersin",
  "Eskişehir",
  "Trabzon",
  "Kayseri",
  "Ajman",
  "Ras Al Khaimah",
  "Fujairah",
  "Al Ain",
  "Mecca",
  "Medina",
  "Khobar",
  "Dhahran",
  "Tabuk",
  "Abha",
  "Sana'a",
  "Aden",
  "Baghdad",
  "Erbil",
  "Basra",
  "Mosul",
  "Tehran",
  "Isfahan",
  "Shiraz",
  "Mashhad",
  "Tabriz",
  "Damascus",
  "Aleppo",
  "Luxor",
  "Aswan",
  "Sharm El Sheikh",
  "Port Said",
  "Fes",
  "Agadir",
  "Meknes",
  "Oujda",
  "Sousse",
  "Monastir",
  "Ife",
  "Abeokuta",
  "Benin City",
  "Jos",
  "Warri",
  "Calabar",
  "Owerri",
  "Onitsha",
  "Aba",
  "Tamale",
  "Takoradi",
  "Bloemfontein",
  "Centurion",
  "Sandton",
  "Stellenbosch",
  "Pretoria, South Africa",
  "Eldoret",
  "Nakuru",
  "Kisumu, Kenya",
  "Arusha",
  "Mwanza",
  "Zanzibar",
  "Gulu",
  "Mbarara",
  "Lilongwe",
  "Blantyre",
  "Ndola",
  "Kitwe",
  "Bulawayo",
  "Mutare",
  "Francistown",
  "Walvis Bay",
  "Beira",
  "Nampula",
  "Benguela",
  "Huambo",
  "Toamasina",
  "Bamako",
  "Ouagadougou",
  "Niamey",
  "N'Djamena",
  "Bangui",
  "Brazzaville",
  "Kinshasa",
  "Lubumbashi",
  "Goma",
  "Bujumbura",
  "Freetown",
  "Monrovia",
  "Conakry",
  "Bissau",
  "Banjul",
  "Praia",
  "Malabo",
  "Libreville",
  "Porto-Novo",
  "Cotonou",
  "Lomé",
  "Asmara",
  "Djibouti City",
  "Mogadishu",
  "Hargeisa",

  // South Asia more
  "Thane",
  "Navi Mumbai",
  "Ghaziabad",
  "Faridabad",
  "Greater Noida",
  "Gandhinagar",
  "Vadodara",
  "Rajkot",
  "Bhavnagar",
  "Trivandrum",
  "Calicut",
  "Kozhikode",
  "Mangalore",
  "Mangaluru",
  "Hubli",
  "Belgaum",
  "Madurai",
  "Tiruchirappalli",
  "Salem, India",
  "Tiruppur",
  "Vellore",
  "Warangal",
  "Vijayawada",
  "Guntur",
  "Tirupati",
  "Bhubaneswar",
  "Cuttack",
  "Ranchi",
  "Jamshedpur",
  "Patna",
  "Gaya",
  "Guwahati",
  "Shillong",
  "Imphal",
  "Agartala",
  "Dehradun",
  "Haridwar",
  "Shimla",
  "Amritsar",
  "Ludhiana",
  "Jalandhar",
  "Kanpur",
  "Agra",
  "Varanasi",
  "Allahabad",
  "Prayagraj",
  "Meerut",
  "Faisalabad",
  "Multan",
  "Peshawar",
  "Quetta",
  "Sialkot",
  "Gujranwala",
  "Hyderabad, Pakistan",
  "Chittagong, Bangladesh",
  "Sylhet",
  "Khulna",
  "Rajshahi",
  "Galle",
  "Jaffna",
  "Negombo",
  "Biratnagar",
  "Lalitpur",
  "Paro",

  // East / SE Asia more
  "Saitama",
  "Chiba",
  "Kawasaki",
  "Sendai",
  "Hiroshima",
  "Okayama",
  "Niigata",
  "Kanazawa",
  "Nagasaki",
  "Kumamoto",
  "Kagoshima",
  "Okinawa",
  "Naha",
  "Gwangju",
  "Ulsan",
  "Suwon",
  "Seongnam",
  "Changwon",
  "Jeonju",
  "Jeju",
  "Dongguan",
  "Foshan",
  "Zhuhai",
  "Zhongshan",
  "Xiamen",
  "Fuzhou",
  "Quanzhou",
  "Ningbo",
  "Wuxi",
  "Changzhou",
  "Suzhou, China",
  "Hefei",
  "Nanchang",
  "Changsha",
  "Zhengzhou",
  "Jinan",
  "Qingdao",
  "Dalian",
  "Shenyang",
  "Harbin",
  "Changchun",
  "Kunming",
  "Guiyang",
  "Nanning",
  "Haikou",
  "Sanya",
  "Lanzhou",
  "Xining",
  "Yinchuan",
  "Hohhot",
  "Ürümqi",
  "Urumqi",
  "Lhasa",
  "Macao",
  "Macau SAR",
  "Hong Kong SAR",
  "New Taipei",
  "Tainan",
  "Hsinchu",
  "Taoyuan",
  "Keelung",
  "Can Tho",
  "Nha Trang",
  "Hue",
  "Vung Tau",
  "Bien Hoa",
  "Hai Phong",
  "Pattaya",
  "Hat Yai",
  "Khon Kaen",
  "Chiang Rai",
  "Udon Thani",
  "Nakhon Ratchasima",
  "George Town",
  "Malacca",
  "Melaka",
  "Kota Kinabalu",
  "Kuching",
  "Shah Alam",
  "Petaling Jaya",
  "Cyberjaya",
  "Putrajaya",
  "Semarang",
  "Makassar",
  "Palembang",
  "Yogyakarta",
  "Jogja",
  "Malang",
  "Bogor",
  "Depok",
  "Tangerang",
  "Bekasi",
  "Batam",
  "Balikpapan",
  "Manado",
  "Padang",
  "Pekanbaru",
  "Pontianak",
  "Cebu City",
  "Iloilo",
  "Cagayan de Oro",
  "Baguio",
  "Taguig",
  "Pasig",
  "Mandaluyong",
  "Parañaque",
  "Las Piñas",
  "Antipolo",
  "Zamboanga",
  "Bacolod",
  "General Santos",
  "Siem Reap, Cambodia",
  "Battambang",
  "Mandalay, Myanmar",
  "Naypyidaw",
  "Luang Prabang",
  "Pakxe",

  // LatAm / Oceania more
  "Campinas, Brazil",
  "Santos",
  "Ribeirão Preto",
  "Uberlândia",
  "Goiânia",
  "Manaus",
  "Belém",
  "Fortaleza",
  "Salvador",
  "Natal",
  "João Pessoa",
  "Maceió",
  "Vitória",
  "Juiz de Fora",
  "São José dos Campos",
  "Joinville",
  "Blumenau",
  "Caxias do Sul",
  "Londrina",
  "Maringá",
  "Teresina",
  "Campo Grande",
  "Cuiabá",
  "La Plata",
  "Mar del Plata",
  "Salta",
  "Tucumán",
  "San Miguel de Tucumán",
  "Neuquén",
  "Bariloche",
  "Valparaíso, Chile",
  "Viña del Mar",
  "Antofagasta",
  "Temuco",
  "Puerto Montt",
  "Iquique",
  "Barranquilla",
  "Bucaramanga",
  "Pereira",
  "Manizales",
  "Ibagué",
  "Cúcuta",
  "Santa Marta",
  "Trujillo",
  "Cusco",
  "Chiclayo",
  "Piura",
  "Iquitos",
  "Cuenca",
  "Manta",
  "Ambato",
  "Cochabamba",
  "Sucre",
  "Ciudad del Este",
  "Encarnación",
  "Maracaibo",
  "Valencia, Venezuela",
  "Barquisimeto",
  "Maracay",
  "Georgetown, Guyana",
  "Paramaribo",
  "Cayenne",
  "San Pedro Sula",
  "San Miguel",
  "León",
  "Liberia, Costa Rica",
  "Heredia",
  "Alajuela",
  "David",
  "Colón",
  "Santiago de los Caballeros",
  "Punta Cana",
  "Montego Bay",
  "Nassau",
  "Freeport",
  "Bridgetown",
  "Castries",
  "Newcastle, Australia",
  "Wollongong",
  "Geelong",
  "Ballarat",
  "Bendigo",
  "Townsville",
  "Cairns",
  "Toowoomba",
  "Sunshine Coast",
  "Wollongong, Australia",
  "Fremantle",
  "Newcastle, NSW",
  "Parramatta",
  "Chatswood",
  "North Sydney",
  "South Brisbane",
  "Tauranga",
  "Hamilton NZ",
  "Napier",
  "Palmerston North",
  "Nelson",
  "Queenstown",
  "Rotorua",
  "Nuku'alofa",
  "Apia",
  "Port Moresby",
  "Honiara",
  "Port Vila",
  "Nouméa",
  "Papeete",
];

/** Still more cities / regions for GitHub location matching */
const EVEN_MORE_LOCATIONS = [
  // US mid-size / tech hubs
  "Huntsville",
  "Chattanooga",
  "Knoxville",
  "Greensboro",
  "Wilmington, NC",
  "Wilmington, DE",
  "Trenton, NJ",
  "Allentown, PA",
  "Harrisburg, PA",
  "State College, PA",
  "Ithaca, NY",
  "Binghamton, NY",
  "Poughkeepsie, NY",
  "New Rochelle, NY",
  "Yonkers, NY",
  "Jersey Shore",
  "Cape Cod",
  "Martha's Vineyard",
  "Nantucket",
  "Newport, RI",
  "Worcester",
  "Lowell, MA",
  "Springfield, MA",
  "Hartford",
  "Bridgeport, CT",
  "Norwalk, CT",
  "Danbury, CT",
  "Portland Maine",
  "Bangor, ME",
  "Burlington Vermont",
  "Montpelier, VT",
  "Concord, NH",
  "Nashua, NH",
  "Lebanon, NH",
  "Charleston, WV",
  "Morgantown, WV",
  "Roanoke, VA",
  "Lynchburg, VA",
  "Fredericksburg, VA",
  "Harrisonburg, VA",
  "Blacksburg, VA",
  "Greenville, NC",
  "Wilmington",
  "Fayetteville, NC",
  "Myrtle Beach, SC",
  "Hilton Head",
  "Augusta",
  "Macon, GA",
  "Columbus, GA",
  "Pensacola, FL",
  "Sarasota, FL",
  "Naples, FL",
  "Key West, FL",
  "Daytona Beach, FL",
  "Melbourne, FL",
  "Palm Beach, FL",
  "Boca Raton, FL",
  "Coral Gables, FL",
  "Hialeah, FL",
  "Tallahassee",
  "Mobile",
  "Tuscaloosa, AL",
  "Biloxi, MS",
  "Gulfport, MS",
  "Shreveport, LA",
  "Baton Rouge, LA",
  "Lafayette, LA",
  "Lake Charles, LA",
  "Texarkana",
  "Beaumont, TX",
  "Corpus Christi, TX",
  "Laredo, TX",
  "McAllen, TX",
  "Brownsville, TX",
  "Waco, TX",
  "Lubbock, TX",
  "Amarillo, TX",
  "Midland, TX",
  "Odessa, TX",
  "Tyler, TX",
  "Denton, TX",
  "Frisco, TX",
  "McKinney, TX",
  "Allen, TX",
  "Richardson, TX",
  "Garland, TX",
  "Mesquite, TX",
  "Grand Prairie, TX",
  "Carrollton, TX",
  "Sugar Land, TX",
  "The Woodlands, TX",
  "Pearland, TX",
  "League City, TX",
  "Katy, TX",
  "Pasadena, TX",
  "Norman, OK",
  "Stillwater, OK",
  "Fayetteville, AR",
  "Springdale, AR",
  "Bentonville, AR",
  "Rogers, AR",
  "Jonesboro, AR",
  "Springfield, MO",
  "Columbia, MO",
  "Jefferson City, MO",
  "Topeka, KS",
  "Lawrence, KS",
  "Manhattan, KS",
  "Overland Park, KS",
  "Olathe, KS",
  "Council Bluffs, IA",
  "Iowa City, IA",
  "Ames, IA",
  "Davenport, IA",
  "Quad Cities",
  "Peoria, IL",
  "Rockford, IL",
  "Champaign, IL",
  "Urbana, IL",
  "Bloomington, IL",
  "Springfield, IL",
  "Gary, IN",
  "South Bend, IN",
  "Evansville, IN",
  "Terre Haute, IN",
  "West Lafayette, IN",
  "Ann Arbor, MI",
  "Kalamazoo, MI",
  "Flint, MI",
  "Dearborn, MI",
  "Troy, MI",
  "Novi, MI",
  "Rochester Hills, MI",
  "Akron",
  "Canton, OH",
  "Youngstown, OH",
  "Athens, OH",
  "Oxford, OH",
  "Bowling Green, OH",
  "Lexington",
  "Bowling Green, KY",
  "Owensboro, KY",
  "Johnson City, TN",
  "Clarksville, TN",
  "Murfreesboro, TN",
  "Franklin, TN",
  "Brentwood, TN",
  "Green Bay, WI",
  "Appleton, WI",
  "Oshkosh, WI",
  "Eau Claire, WI",
  "La Crosse, WI",
  "Duluth, MN",
  "Rochester Minnesota",
  "Bloomington, MN",
  "Eden Prairie, MN",
  "Minnetonka, MN",
  "St Cloud, MN",
  "Fargo",
  "Bismarck, ND",
  "Grand Forks, ND",
  "Rapid City, SD",
  "Billings, MT",
  "Missoula, MT",
  "Bozeman, MT",
  "Helena, MT",
  "Cheyenne, WY",
  "Jackson, WY",
  "Jackson Hole",
  "Idaho Falls, ID",
  "Coeur d'Alene, ID",
  "Twin Falls, ID",
  "Spokane Valley, WA",
  "Vancouver, WA",
  "Bellingham, WA",
  "Olympia",
  "Bremerton, WA",
  "Everett, WA",
  "Kirkland, WA",
  "Redmond",
  "Bellevue",
  "Issaquah, WA",
  "Sammamish, WA",
  "Mercer Island, WA",
  "Bend",
  "Medford, OR",
  "Corvallis, OR",
  "Ashland, OR",
  "Hood River, OR",
  "Reno",
  "Carson City, NV",
  "Henderson, NV",
  "Paradise, NV",
  "Summerlin, NV",
  "St George, UT",
  "Logan, UT",
  "Orem, UT",
  "Lehi, UT",
  "American Fork, UT",
  "Draper, UT",
  "Sandy, UT",
  "West Jordan, UT",
  "Flagstaff",
  "Sedona, AZ",
  "Yuma, AZ",
  "Prescott, AZ",
  "Gilbert, AZ",
  "Peoria, AZ",
  "Glendale, AZ",
  "Surprise, AZ",
  "Santa Fe",
  "Las Cruces, NM",
  "Rio Rancho, NM",
  "Taos, NM",
  "Pueblo, CO",
  "Greeley, CO",
  "Longmont, CO",
  "Loveland, CO",
  "Breckenridge, CO",
  "Vail, CO",
  "Aspen",
  "Telluride, CO",
  "Durango, CO",
  "Grand Junction, CO",
  "Honolulu",
  "Maui",
  "Kailua, HI",
  "Hilo, HI",
  "Kahului, HI",
  "Anchorage",
  "Fairbanks, AK",
  "Juneau, AK",
  "Sitka, AK",

  // California denser
  "Berkeley",
  "Oakland",
  "Emeryville, CA",
  "Alameda, CA",
  "Hayward, CA",
  "San Leandro, CA",
  "Dublin, CA",
  "Livermore, CA",
  "Tracy, CA",
  "Stockton, CA",
  "Modesto, CA",
  "Merced, CA",
  "Visalia, CA",
  "Clovis, CA",
  "Hanford, CA",
  "Salinas, CA",
  "Monterey, CA",
  "Carmel, CA",
  "Santa Cruz",
  "Watsonville, CA",
  "Gilroy, CA",
  "Morgan Hill, CA",
  "Los Gatos, CA",
  "Saratoga, CA",
  "Cupertino",
  "Los Altos, CA",
  "Mountain View",
  "Palo Alto",
  "Stanford, CA",
  "Menlo Park",
  "Atherton, CA",
  "Woodside, CA",
  "Portola Valley, CA",
  "Half Moon Bay, CA",
  "Pacifica, CA",
  "Daly City, CA",
  "South San Francisco, CA",
  "Burlingame, CA",
  "San Bruno, CA",
  "Millbrae, CA",
  "Foster City, CA",
  "Belmont, CA",
  "San Carlos, CA",
  "Redwood City",
  "East Palo Alto, CA",
  "Sunnyvale",
  "Santa Clara",
  "Campbell, CA",
  "Cupertino, CA",
  "Milpitas",
  "Newark, CA",
  "Union City, CA",
  "Fremont",
  "San Jose",
  "Los Angeles",
  "Hollywood, CA",
  "West Hollywood, CA",
  "Beverly Hills, CA",
  "Santa Monica",
  "Venice, CA",
  "Marina del Rey, CA",
  "Culver City, CA",
  "El Segundo, CA",
  "Manhattan Beach, CA",
  "Hermosa Beach, CA",
  "Redondo Beach, CA",
  "Torrance, CA",
  "Long Beach",
  "Pasadena",
  "Glendale, CA",
  "Burbank, CA",
  "North Hollywood, CA",
  "Sherman Oaks, CA",
  "Encino, CA",
  "Woodland Hills, CA",
  "Calabasas, CA",
  "Malibu, CA",
  "Thousand Oaks, CA",
  "Oxnard, CA",
  "Ventura, CA",
  "Camarillo, CA",
  "Santa Barbara",
  "Goleta, CA",
  "San Luis Obispo, CA",
  "Paso Robles, CA",
  "Bakersfield",
  "Palmdale, CA",
  "Lancaster, CA",
  "Victorville, CA",
  "Rancho Cucamonga, CA",
  "Ontario, CA",
  "Pomona, CA",
  "Claremont, CA",
  "Riverside, CA",
  "San Bernardino, CA",
  "Redlands, CA",
  "Palm Springs, CA",
  "Palm Desert, CA",
  "Indio, CA",
  "Irvine",
  "Newport Beach, CA",
  "Costa Mesa, CA",
  "Huntington Beach, CA",
  "Fountain Valley, CA",
  "Anaheim, CA",
  "Orange, CA",
  "Fullerton, CA",
  "Santa Ana, CA",
  "Tustin, CA",
  "Mission Viejo, CA",
  "Laguna Beach, CA",
  "San Clemente, CA",
  "Carlsbad, CA",
  "Oceanside, CA",
  "Encinitas, CA",
  "Del Mar, CA",
  "La Jolla, CA",
  "San Diego",
  "Chula Vista, CA",
  "Escondido, CA",
  "Temecula, CA",
  "Murrieta, CA",
  "Sacramento",
  "Davis, CA",
  "Woodland, CA",
  "Roseville, CA",
  "Rocklin, CA",
  "Folsom, CA",
  "Elk Grove, CA",
  "Napa, CA",
  "Sonoma, CA",
  "Santa Rosa, CA",
  "Petaluma, CA",
  "Novato, CA",
  "San Rafael",
  "Mill Valley, CA",
  "Sausalito, CA",
  "Tiburon, CA",
  "Vallejo, CA",
  "Fairfield, CA",
  "Vacaville, CA",
  "Chico, CA",
  "Redding, CA",
  "Eureka, CA",
  "Tahoe",
  "Lake Tahoe",
  "South Lake Tahoe, CA",
  "Truckee, CA",
  "Yosemite",
  "Mammoth Lakes, CA",

  // International denser fill
  "Reading, UK",
  "Oxford, UK",
  "Cambridge, UK",
  "Canterbury, UK",
  "Winchester, UK",
  "Chester, UK",
  "Durham, UK",
  "Lancaster, UK",
  "Preston, UK",
  "Blackpool, UK",
  "Bolton, UK",
  "Wigan, UK",
  "Warrington, UK",
  "Stoke-on-Trent",
  "Wolverhampton",
  "Walsall",
  "Solihull",
  "Coventry, UK",
  "Leicester, UK",
  "Derby, UK",
  "Nottingham, UK",
  "Sheffield, UK",
  "Doncaster",
  "Hull",
  "Kingston upon Hull",
  "York, UK",
  "Harrogate",
  "Middlesbrough",
  "Sunderland",
  "Gateshead",
  "South Shields",
  "Carlisle",
  "Kendal",
  "Windermere",
  "Truro",
  "Falmouth",
  "Newquay",
  "Penzance",
  "Torquay",
  "Exeter, UK",
  "Plymouth, UK",
  "Bournemouth, UK",
  "Poole",
  "Salisbury",
  "Guildford, UK",
  "Woking",
  "Crawley",
  "Horsham",
  "Worthing",
  "Eastbourne",
  "Hastings",
  "Tunbridge Wells",
  "Maidstone",
  "Ashford, UK",
  "Dover",
  "Folkestone",
  "Southend-on-Sea",
  "Basildon",
  "Chelmsford",
  "Colchester",
  "Ipswich, UK",
  "Norwich, UK",
  "Peterborough",
  "Bedford",
  "Luton",
  "Watford",
  "St Albans",
  "Hemel Hempstead",
  "Stevenage",
  "Welwyn Garden City",
  "Hatfield",
  "Croydon",
  "Bromley",
  "Kingston upon Thames",
  "Richmond upon Thames",
  "Wimbledon",
  "Chelsea",
  "Kensington",
  "Canary Wharf",
  "Shoreditch",
  "Hackney",
  "Islington",
  "Camden",
  "Westminster",
  "City of London",
  "Stratford, London",
  "Greenwich",
  "Woolwich",
  "Wembley",
  "Ealing",
  "Hounslow",
  "Heathrow",
  "Gatwick",
  "Stanstead",
  "Luton Airport",

  // India IT hubs denser
  "Whitefield, Bangalore",
  "Koramangala",
  "Indiranagar",
  "HSR Layout",
  "Electronic City",
  "Manyata Tech Park",
  "Outer Ring Road, Bangalore",
  "Gachibowli",
  "Hitech City",
  "Madhapur",
  "Banjara Hills",
  "Jubilee Hills",
  "Secunderabad",
  "OMR, Chennai",
  "T Nagar",
  "Adyar",
  "Guindy",
  "Sholinganallur",
  "Andheri",
  "Bandra",
  "Powai",
  "Lower Parel",
  "Worli",
  "BKC",
  "Navi Mumbai",
  "Thane",
  "Pune IT Park",
  "Hinjewadi",
  "Kharadi",
  "Baner",
  "Wakad",
  "Viman Nagar",
  "Koregaon Park",
  "Cyber City, Gurgaon",
  "Golf Course Road",
  "Sector 62, Noida",
  "Sector 18, Noida",
  "Connaught Place",
  "Nehru Place",
  "Okhla",
  "Dwarka",
  "Salt Lake, Kolkata",
  "Sector V, Kolkata",
  "Rajarhat",
  "New Town, Kolkata",
  "Technopark, Trivandrum",
  "Infopark, Kochi",
  "SEZ",
  "STP",

  // More world capitals / major cities not already listed
  "Ottawa, Canada",
  "Canberra, Australia",
  "Wellington, New Zealand",
  "Brasília, Brazil",
  "Buenos Aires, Argentina",
  "Santiago, Chile",
  "Lima, Peru",
  "Bogotá, Colombia",
  "Caracas, Venezuela",
  "Quito, Ecuador",
  "La Paz, Bolivia",
  "Asunción, Paraguay",
  "Montevideo, Uruguay",
  "Mexico City, Mexico",
  "Havana, Cuba",
  "Kingston, Jamaica",
  "Port-au-Prince",
  "Santo Domingo, Dominican Republic",
  "San Juan, Puerto Rico",
  "Panama City, Panama",
  "San José, Costa Rica",
  "Guatemala City, Guatemala",
  "Tegucigalpa, Honduras",
  "San Salvador, El Salvador",
  "Managua, Nicaragua",
  "Belmopan",
  "Nassau, Bahamas",
  "Bridgetown, Barbados",
  "Castries, Saint Lucia",
  "Kingstown",
  "St. George's",
  "Roseau",
  "Basseterre",
  "Oranjestad",
  "Willemstad",
  "George Town, Cayman Islands",
  "Hamilton, Bermuda",
  "Reykjavik, Iceland",
  "Dublin, Ireland",
  "Lisbon, Portugal",
  "Madrid, Spain",
  "Paris, France",
  "Brussels, Belgium",
  "Amsterdam, Netherlands",
  "Luxembourg City",
  "Berlin, Germany",
  "Bern, Switzerland",
  "Vienna, Austria",
  "Rome, Italy",
  "Vatican City",
  "Valletta, Malta",
  "Athens, Greece",
  "Nicosia, Cyprus",
  "Ankara, Turkey",
  "Moscow, Russia",
  "Kyiv, Ukraine",
  "Minsk, Belarus",
  "Chișinău, Moldova",
  "Bucharest, Romania",
  "Sofia, Bulgaria",
  "Belgrade, Serbia",
  "Zagreb, Croatia",
  "Ljubljana, Slovenia",
  "Sarajevo, Bosnia",
  "Podgorica, Montenegro",
  "Skopje, North Macedonia",
  "Tirana, Albania",
  "Pristina, Kosovo",
  "Budapest, Hungary",
  "Bratislava, Slovakia",
  "Prague, Czech Republic",
  "Warsaw, Poland",
  "Vilnius, Lithuania",
  "Riga, Latvia",
  "Tallinn, Estonia",
  "Helsinki, Finland",
  "Stockholm, Sweden",
  "Oslo, Norway",
  "Copenhagen, Denmark",
  "Cairo, Egypt",
  "Khartoum, Sudan",
  "Addis Ababa, Ethiopia",
  "Nairobi, Kenya",
  "Kampala, Uganda",
  "Kigali, Rwanda",
  "Bujumbura, Burundi",
  "Dar es Salaam, Tanzania",
  "Lilongwe, Malawi",
  "Lusaka, Zambia",
  "Harare, Zimbabwe",
  "Gaborone, Botswana",
  "Windhoek, Namibia",
  "Pretoria, South Africa",
  "Maseru",
  "Mbabane",
  "Maputo, Mozambique",
  "Antananarivo, Madagascar",
  "Port Louis, Mauritius",
  "Victoria, Seychelles",
  "Moroni",
  "Djibouti",
  "Asmara, Eritrea",
  "Mogadishu, Somalia",
  "Juba, South Sudan",
  "Bangui, CAR",
  "N'Djamena, Chad",
  "Niamey, Niger",
  "Ouagadougou, Burkina Faso",
  "Bamako, Mali",
  "Dakar, Senegal",
  "Banjul, Gambia",
  "Bissau, Guinea-Bissau",
  "Conakry, Guinea",
  "Freetown, Sierra Leone",
  "Monrovia, Liberia",
  "Abidjan, Ivory Coast",
  "Yamoussoukro",
  "Accra, Ghana",
  "Lomé, Togo",
  "Cotonou, Benin",
  "Porto-Novo, Benin",
  "Abuja, Nigeria",
  "Yaoundé, Cameroon",
  "Malabo, Equatorial Guinea",
  "Libreville, Gabon",
  "Brazzaville, Congo",
  "Kinshasa, DRC",
  "Luanda, Angola",
  "Praia, Cape Verde",
  "São Tomé",
  "Rabat, Morocco",
  "Algiers, Algeria",
  "Tunis, Tunisia",
  "Tripoli, Libya",
  "Jerusalem, Israel",
  "Amman, Jordan",
  "Beirut, Lebanon",
  "Damascus, Syria",
  "Baghdad, Iraq",
  "Tehran, Iran",
  "Kabul, Afghanistan",
  "Islamabad, Pakistan",
  "New Delhi, India",
  "Kathmandu, Nepal",
  "Thimphu, Bhutan",
  "Dhaka, Bangladesh",
  "Colombo, Sri Lanka",
  "Male, Maldives",
  "Yangon, Myanmar",
  "Naypyidaw, Myanmar",
  "Bangkok, Thailand",
  "Vientiane, Laos",
  "Phnom Penh, Cambodia",
  "Hanoi, Vietnam",
  "Kuala Lumpur, Malaysia",
  "Singapore City",
  "Jakarta, Indonesia",
  "Bandar Seri Begawan",
  "Manila, Philippines",
  "Dili",
  "Beijing, China",
  "Tokyo, Japan",
  "Seoul, South Korea",
  "Pyongyang",
  "Ulaanbaatar, Mongolia",
  "Taipei, Taiwan",
  "Hong Kong, China",
  "Macau, China",
  "Tashkent, Uzbekistan",
  "Bishkek, Kyrgyzstan",
  "Dushanbe, Tajikistan",
  "Ashgabat, Turkmenistan",
  "Astana, Kazakhstan",
  "Nur-Sultan, Kazakhstan",
  "Baku, Azerbaijan",
  "Yerevan, Armenia",
  "Tbilisi, Georgia",
  "Ankara",
  "Nicosia",
  "Canberra",
  "Wellington",
  "Port Moresby, Papua New Guinea",
  "Honiara, Solomon Islands",
  "Port Vila, Vanuatu",
  "Suva, Fiji",
  "Nuku'alofa, Tonga",
  "Apia, Samoa",
  "Funafuti",
  "Tarawa",
  "Majuro",
  "Palikir",
  "Yaren",
  "Ngerulmud",
  "South Tarawa",
];

const LOCATIONS = [
  "Remote",
  ...FEATURED,
  ...ALL_COUNTRIES,
  ...CITIES,
  ...MORE_LOCATIONS,
  ...EVEN_MORE_LOCATIONS,
  ...ASIA_CITIES,
];

function uniquePreserveOrder(items: string[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const item of items) {
    const key = item.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(item);
  }
  return out;
}

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const q = (searchParams.get("q") || "").trim().toLowerCase();
  const all = uniquePreserveOrder(LOCATIONS);

  if (!q) {
    return NextResponse.json(all);
  }

  const starts = all.filter((l) => l.toLowerCase().startsWith(q));
  const contains = all.filter(
    (l) => !l.toLowerCase().startsWith(q) && l.toLowerCase().includes(q)
  );
  // Return full match set (no hard 40 cap) so every country/city is reachable
  return NextResponse.json([...starts, ...contains]);
}
